package interfaz;

import vistas.VistaVer_mas_canciones_favoritas;

public class Ver_mas_canciones_favoritas extends VistaVer_mas_canciones_favoritas{
	public Canciones_favoritas _cancionesFavoritas;
	public Lista_de_reproduccion_favoritos _listaDeReproduccionFavoritos;
}